SECTIONS_WHITELIST = {
    "I. Disposiciones generales",
    "III. Otras disposiciones",
}

DEPARTMENTS_WHITELIST = {
    "MINISTERIO DE TRABAJO Y ECONOMÍA SOCIAL",
        "MINISTERIO DE INCLUSIÓN, SEGURIDAD SOCIAL Y MIGRACIONES",
        "MINISTERIO DE HACIENDA",
        "MINISTERIO DE ECONOMÍA, COMERCIO Y EMPRESA",
        "MINISTERIO DE INDUSTRIA Y TURISMO",
        "MINISTERIO DE DERECHOS SOCIALES, CONSUMO Y AGENDA 2030",
        "MINISTERIO PARA LA TRANSICIÓN ECOLÓGICA Y EL RETO DEMOGRÁFICO",
        "MINISTERIO DE SANIDAD",
        "MINISTERIO DE TRANSPORTES Y MOVILIDAD SOSTENIBLE",
        "MINISTERIO PARA LA TRANSFORMACIÓN DIGITAL Y DE LA FUNCIÓN PÚBLICA",
        "BANCO DE ESPAÑA",
}